spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/transportdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080

telegram:
  bot:
    token: "7866843638:AAGOI19M3acDL3VY1L2JNsOfSylsjjjAF20"
    username: "@ololo_travel_bot"