spring:
  data:
    host: localhost
    port: 27017
    database: transport_db
    mongodb:
      uri: mongodb://localhost:27017/transport_db
server:
  ssl:
    enabled: false
  port: 7070

telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://public-carrots-like.loca.lt"
  bot-name: "ololotravelbot"
  bot-token: "8063211434:AAGFNMwI-kStDKucYlLz4qm4xijnY7NYuu4"